### ISSUE TITLE
Response encoding

### ISSUE THREAD

**Issue by BruTyler** [prom-client-net/Prometheus.Client.AspNetCore#16]
Hi! We've met a problem to display cyrillic letters -  because response didn't contain correct charset in header, User-agent chose the best default option. Google Chrome, for example, thaught that utf-8 text was encoded in win-1251.

What about making options are more flexible with Charset Encodind as a parameter?
   ```app.UsePrometheusServer(q =>
    {
        q.ResponseEncoding= Encoding.UTF8;
    });```

**Comment by phnx47** [comment]
Published: [v4.4.0](https://www.nuget.org/packages/Prometheus.Client.AspNetCore/4.4.0)
